########Input FILES########
mtc_assembly: Path/mtc1,Path/mtc2 (...)
ncl_assembly: Path/ncl1,Path/ncl2 (...)
forward_read: Path/forward_read1,Path/forward_read2 (...)
reverse_read: Path/reverse_read1,Path/reverse_read2 (...)
###########################

input_organism: ID_1,ID_2 (...)


#######Adapter for Trimming #########
adapters: PATH_adapters_trimming/bbmap-38.22-0/resources/adapters.fa



